<a href="https://colab.research.google.com/github/jeromepatel/DL-University-Course-Practicals/blob/master/18BCE088_DL_practical_1_MLPC_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MLP Classifier for MNIST dataset using Sklearn

In [ ]:
#importing libraries
from keras.datasets.mnist import load_data
from matplotlib import pyplot
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
(X_train, Y_train), (X_test, Y_test) = load_data()
X_train.shape, X_test.shape

((60000, 28, 28), (10000, 28, 28))

In [ ]:
#reshaping to training and test set for sequential input 
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1] * X_train.shape[2])

X_test = X_test.reshape(X_test.shape[0], X_test.shape[1] * X_test.shape[2])
X_train.shape, X_test.shape

((60000, 784), (10000, 784))

In [ ]:
# X_train = (X_train - 127.5)/127.5  #getting image in range of [-1,1] for train set 
# X_test = (X_test - 127.5)/127.5  #getting in range of [-1,1] for test set 

X_train = X_train/255   #in range (0,1) now 
X_test = X_test/255

In [ ]:
#classifying using MLP Classifier 
# clf = MLPClassifier(hidden_layer_sizes=(392,), max_iter=10, alpha=7e-4,
#                     solver='sgd',learning_rate='adaptive', verbose=10, random_state=2,
#                     learning_rate_init=.03)
clf = MLPClassifier(hidden_layer_sizes=(392,50),solver='adam',learning_rate='adaptive',alpha= 3e-4, random_state=2, max_iter=10, verbose = True)
#training on training dataset
clf.fit(X_train, Y_train)


Iteration 1, loss = 0.30470271
Iteration 2, loss = 0.11279152
Iteration 3, loss = 0.07472919
Iteration 4, loss = 0.05499526
Iteration 5, loss = 0.03860631
Iteration 6, loss = 0.03014604
Iteration 7, loss = 0.02117879
Iteration 8, loss = 0.01613411
Iteration 9, loss = 0.01390404
Iteration 10, loss = 0.01160031


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0003, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(392, 50), learning_rate='adaptive',
              learning_rate_init=0.001, max_fun=15000, max_iter=10,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=2, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=True,
              warm_start=False)

In [ ]:

#prediction using test set
preds = clf.predict(X_test)
score = accuracy_score(preds, Y_test)
print(f'accuracy score for the MNIST classification of the dataset is : {score}')

accuracy score for the MNIST classification of the dataset is : 0.9808


In [ ]:
print(f"confusion matrix is \n{confusion_matrix(preds,Y_test)}\n and classification report is \n{classification_report(preds,Y_test)}")

confusion matrix is 
[[ 960    0    3    0    3    3    4    1    0    1]
 [   0 1124    2    0    0    0    2    5    0    2]
 [   1    0  987    2    1    0    1    8    0    0]
 [   0    1   11  985    0    8    1    5    2    6]
 [   0    0    2    0  944    0    1    1    3    4]
 [   3    0    0    7    3  876   10    0    3    7]
 [   5    2    1    0    7    2  936    1    2    2]
 [   1    0    4    1    2    0    0  977    0    1]
 [   7    8   21    9    3    1    3   13  963    7]
 [   3    0    1    6   19    2    0   17    1  979]]
 and classification report is 
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       975
           1       0.99      0.99      0.99      1135
           2       0.96      0.99      0.97      1000
           3       0.98      0.97      0.97      1019
           4       0.96      0.99      0.97       955
           5       0.98      0.96      0.97       909
           6       0.98      0.98     